import { Moment } from 'moment';
// Generated by https://quicktype.io

export type EstadoType = 'En-espera' | 'Cancelada' | 'Finalizada' | 'Atendiendo'

export type citaHoraType = {
    hora: string;
    fecha: number;
}

export type paginationType = {
    page: number;
    total: number;
    start?: Moment;
    end?: Moment;
}

export interface CitasInterface {
    ok?:   boolean;
    cita: CitasInterfaceCita[];
    isOpen: boolean;
    citaActiva?: CitasInterfaceCita | null
    pagination?: paginationType | null
}

export interface CitasInterfaceCita {
    _id:       string;
    userId:    string;
    cita:      CitaCita[];
    ninos:     boolean;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}

export interface nuevaCitasInterfaceCita {
    _id:       string;
    barberId:  string;
    usuarioId: string;
    hora:      citaHoraType;
    servicio:  Servicio[];
    nombre:    string;
    ninos:     boolean;
    estado:    EstadoType;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}

export interface CitaCita {
    barberId:  string;
    usuarioId: string;
    barberName: string;
    hora:      citaHoraType;
    servicio:  Servicio[];
    nombre:    string;
    estado:    EstadoType;
}

export interface citasAtenderIt {
    _id: string;
    barberId: string;
    usuarioId: string;
    barberName: string;
    hora: citaHoraType;
    servicio: Servicio[];
    nombre: string;
    estado: EstadoType;
}

export interface Servicio {
    servicio: string;
    tiempo:   string;
    minHor:   string;
}
