// Generated by https://quicktype.io

type EstadoType = 'En-espera' | 'Cancelada' | 'Finalizada' | 'Recortando'

export interface CitasInterface {
    ok?:   boolean;
    cita: CitasInterfaceCita[];
    isOpen: boolean;
}

export interface CitasInterfaceCita {
    _id:       string;
    cita:      CitaCita[];
    ninos:     boolean;
    estado:    EstadoType;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}

export interface nuevaCitasInterfaceCita {
    _id:       string;
    barberId:  string;
    usuarioId: string;
    hora:      string;
    servicio:  Servicio[];
    nombre:    string;
    ninos:     boolean;
    estado:    EstadoType;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}

export interface CitaCita {
    barberId:  string;
    usuarioId: string;
    hora:      string;
    servicio:  Servicio[];
    nombre:    string;
}

export interface Servicio {
    servicio: string;
    tiempo:   string;
    minHor:   string;
}
