// Generated by https://quicktype.io

export interface NegocioProps {
    ok?:      boolean;
    negocio: Negocio[];
}

export interface Negocio {
    _id:           string;
    barberId:      string;
    servicios:     Servicio[];
    ubicacion:     Ubicacion[];
    horas?:         Horas;
    horasClientes: Hora[];
    createdAt:     string;
    updatedAt:     string;
    __v:           number;
    xTiempo?:       XTiempo;
    horarioDia?:    Hora[];
}

export interface Hora {
    fecha:    number;
    hora:     string;
    selected: boolean | string;
}

export interface Horas {
    desde: string;
    hasta: string;
}

export interface Servicio {
    servicio: string;
    tiempo:   string;
    minHor:   string;
}

export interface Ubicacion {
    ubicacion: string;
    link:      string;
}

export interface XTiempo {
    cantidad: number;
    tiempo:   string;
}
