// Generated by https://quicktype.io

export interface Usuarios {
    ok:      boolean;
    usuario: Usuario;
    msg?:     string;
    token?: string;
}

export interface Usuario {
    name:      string;
    lastName:  string;
    email:     string;
    password:  string;
    _id:       string;
    ratingForm: RatingFormType[];
    createdAt: string;
    updatedAt: string;
    __v:       number;
}

export interface RatingFormType {
    usuarioId: string;
    barberId: string;
    calificacion: number;
}

export interface UsuarioPost {
    name:      string;
    lastName:  string;
    email:     string;
    password:  string;
}

export interface UsuarioLogin {
    email:     string;
    password:  string;
}
